### ISSUE TITLE
Resource fails when setting owner

### ISSUE THREAD

**Issue by wolf31o2** [chef-cookbooks/ark#181]
### Cookbook version
2.2.0

### Chef-client version
12.4.3

### Platform Details
Happens reliably in automated testing on every platform I've tested.

### Scenario:
Use `ark` resource w/ `owner` attribute.

### Steps to Reproduce:
Use `ark` resource w/ `owner` attribute set.

### Expected Result:
Extract my ZIP file.

### Actual Result:
```
    cdap-sdk-ami: ================================================================================
    cdap-sdk-ami: Error executing action `install` on resource 'ark[sdk]'
    cdap-sdk-ami: ================================================================================
    cdap-sdk-ami:
    cdap-sdk-ami: NoMethodError
    cdap-sdk-ami: -------------
    cdap-sdk-ami: undefined method `owner=' for LWRP resource ark from cookbook ark
```

**Comment by wolf31o2** [comment]
Pretty sure that this was introduced with #171 and using `2.1.0` doesn't exhibit this behavior.

**Comment by drenalin23** [comment]
Confirmed that this fails in our auomated travis setup.  Chef 12.4.1.
We just started seeing this today with the latest release here.

NoMethodError
-------------
undefined method `owner=' for LWRP resource ark from cookbook ark

**Comment by dereklwood** [comment]
Submitted fix in #182
